add_library(curvature_estimator_parallel INTERFACE)

if(HAVE_OPENCL)
    add_subdirectory(OpenCL)
    if(TARGET curvature_estimator_opencl)
        target_link_libraries(curvature_estimator_parallel INTERFACE curvature_estimator_opencl)
    endif()
endif()

if(HAVE_VULKAN)
    add_subdirectory(Vulkan)
    if(TARGET curvature_estimator_vulkan)
        target_link_libraries(curvature_estimator_parallel INTERFACE curvature_estimator_vulkan)
    endif()
endif()

if(HAVE_CUDA)
    add_subdirectory(Cuda)
    if(TARGET curvature_estimator_cuda)
        target_link_libraries(curvature_estimator_parallel INTERFACE curvature_estimator_cuda)
    endif()
endif()

if(HAVE_DIRECTX)
    add_subdirectory(DirectX)
    if(TARGET curvature_estimator_directx)
        target_link_libraries(curvature_estimator_parallel INTERFACE curvature_estimator_directx)
    endif()
endif()

if(HAVE_METAL)
    add_subdirectory(Metal)
    if(TARGET curvature_estimator_metal)
        target_link_libraries(curvature_estimator_parallel INTERFACE curvature_estimator_metal)
    endif()
endif()
