add_library(voxelizer_parallel INTERFACE)

if(HAVE_OPENCL)
    add_subdirectory(OpenCL)
    if(TARGET voxelizer_opencl)
        target_link_libraries(voxelizer_parallel INTERFACE voxelizer_opencl)
    endif()
endif()

if(HAVE_VULKAN)
    add_subdirectory(Vulkan)
    if(TARGET voxelizer_vulkan)
        target_link_libraries(voxelizer_parallel INTERFACE voxelizer_vulkan)
    endif()
endif()

if(HAVE_CUDA)
    add_subdirectory(Cuda)
    if(TARGET voxelizer_cuda)
        target_link_libraries(voxelizer_parallel INTERFACE voxelizer_cuda)
    endif()
endif()

if(HAVE_DIRECTX)
    add_subdirectory(DirectX)
    if(TARGET voxelizer_directx)
        target_link_libraries(voxelizer_parallel INTERFACE voxelizer_directx)
    endif()
endif()

if(HAVE_METAL)
    add_subdirectory(Metal)
    if(TARGET voxelizer_metal)
        target_link_libraries(voxelizer_parallel INTERFACE voxelizer_metal)
    endif()
endif()
